services:
  web:
    build: .
    container_name: file_converter_api
    ports:
      - "1984:8000"
    volumes:
      - ./app:/code/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped